# Generated by Django 2.2.1 on 2019-06-02 00:27

import apps.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FindRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to=apps.utils.default_image_path, verbose_name='이미지')),
                ('contact', models.CharField(max_length=250, verbose_name='연락처')),
                ('status', models.CharField(choices=[('ready', 'ready'), ('fail', 'fail'), ('success', 'success')], default='ready', max_length=250, verbose_name='상태')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=250, verbose_name='장소')),
                ('azure_on', models.BooleanField(default=False, verbose_name='에저그룹생성')),
            ],
        ),
        migrations.CreateModel(
            name='Refugee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to=apps.utils.default_image_path, verbose_name='이미지')),
                ('status', models.CharField(choices=[('alive', 'alive'), ('death', 'death'), ('moveout', 'moveout')], max_length=250, verbose_name='상태')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Shelter', verbose_name='피난처')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FindResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('percent', models.CharField(max_length=250, verbose_name='일치도')),
                ('find_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='find_results', to='apps.FindRequest', verbose_name='찾기요청')),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apps.Refugee', verbose_name='실종자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
