# Generated by Django 2.2.1 on 2019-06-02 02:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefugeeFaceAddResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_recognized', models.BooleanField(verbose_name='인식여부')),
                ('persisted_face_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='인식아이디')),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Refugee', verbose_name='등록결과')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
